### ISSUE TITLE
Problem with angular in symlinked modules

### ISSUE THREAD

**Issue by ds82** [thymikee/jest-preset-angular#124]
I have two separate angular libs A and B, whereas A has B as a dependency. During development, B is symlinked to A's node_modules folder (automatically using lerna). A & B both have angular installed locally ..

I've already had problems with this setup when setting up a demo app in A, because ``@angular/*`` modules where loaded partly from ``A/node_modules/@angular/...`` and partly from ``A/node_modules/B/node_modules/@angular/...``. I fixed this by modifying A's  ``tsconfig.json`` like this:

```
{
  "compilerOptions": {
    ...
    "paths": {
      "@angular/*": ["./node_modules/@angular/*"],
      "reflect-metadata": ["./node_modules/reflect-metadata"]
    }
  },
}
```

This ensures that only A's @angular deps are loaded in the demo app of A.
Unfortunately, the jest tests still have the problem of loading a mix of angular deps from A and B.
This leads to errors like this in tests:

```
Unexpected value 'TranslateModule' imported by the module 'CommonInstallationComponentsModule'. Please add a @NgModule annotation
```

I verified that it is actually the same problem by removing B's node_modules folder. When I do this, all tests run fine.

Any idea why this happens or how to fix it? Why is the jest test runner not respecting the tsconfig paths entries? (I also modified src/tsconfig.spec.json and added the path entries ..).

**Comment by thymikee** [comment]
Try to mimic this config in jest's "moduleNameMapper", see this example: https://github.com/thymikee/jest-preset-angular#exposed-configuration

TypeScript, or Babel are just transforms that Jest applies to your code - module resolution is a separate concern, and Jest has it's own logic, that's why it doesn't follow `compilerOptions`, or any other resolution-related options. Technically, someone from TS community, eg. as a part of `ts-jest` project could implement [custom Jest resolver](https://facebook.github.io/jest/docs/en/configuration.html#resolver-string).

**Comment by ds82** [comment]
Wow, thanks .. that worked straightway. For others who have a similar problem, I added this ``moduleNameMapper`` entries:

```
    "moduleNameMapper": {
      "@angular/(.*)": "<rootDir>/node_modules/@angular/$1",
      "reflect-metadata": "<rootDir>/node_modules/reflect-metadata"
    }
```

Awesome! Thanks a lot @thymikee!
