### ISSUE TITLE
"Unexpected token import" for setupJest.ts

### ISSUE THREAD

**Issue by aloifolia** [thymikee/jest-preset-angular#147]
When I run jest, there is some problem with import statements:

```
FAIL  app/foo.service.spec.ts
  ● Test suite failed to run

    /project_path/app/test/setupJest.ts:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){require('ts-jest').install("/project_path/app/test/setupJest.ts", "import 'jest-preset-angular';\nimport './jestGlobalMocks';\n//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoic2V0dXBKZXN0LmpzIiwic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsic2V0dXBKZXN0LnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBLE9BQU8scUJBQXFCLENBQUM7QUFDN0IsT0FBTyxtQkFBbUIsQ0FBQyIsInNvdXJjZXNDb250ZW50IjpbImltcG9ydCAnamVzdC1wcmVzZXQtYW5ndWxhcic7XG5pbXBvcnQgJy4vamVzdEdsb2JhbE1vY2tzJztcbiJdfQ==");import 'jest-preset-angular';


    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:316:17)
```

Is this a bug or could it be a misconfiguration (which might be the case since my config is a mixture of the instructions on Github and on [xfive](https://www.xfive.co/blog/testing-angular-faster-jest/)?

**Comment by AhnpGit** [comment]
Hi @aloifolia, can you please us provide your sample project ? I think your setupJest.ts failed to import jest-preset-angular.
Another hint is you can follow the setup of the example app in this repository.

**Comment by aloifolia** [comment]
@AhnpGit I extracted the project setup to [this project](https://github.com/aloifolia/jest-preset-angular-fail). Fortunately, the error persists.

**Comment by AhnpGit** [comment]
@aloifolia I took a quick look at your repo. 1st of all your repo is not an Angular app. This preset only works with Angular app so if you generate an Angular app using Angular CLI or simply copy example app in the repository and follow the README setup, you should have a working project.

The error you encounter is caused by the line `import 'jest-preset-angular';` . By default, an Angular app uses webpack resolves path which will automatically look for `node_modules/jest-preset-angular` and perform the import. In your repo there is no webpack config therefore it can't find the dependency `jest-preset-angular` in your `node_modules`
