### ISSUE TITLE
Remove rxjs from imports

### ISSUE THREAD

**Issue by thymikee** [thymikee/jest-preset-angular#17]
As stated here: https://github.com/angular/angular-cli/issues/4543#issuecomment-293772490.
It shouldn't be auto included. Although need to add a guide on some useful imports like: 
```js
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/switchMap';
import 'rxjs/add/operator/do';
import 'rxjs/add/operator/catch';
```

**Comment by thymikee** [comment]
For lots of folks it would be a breaking change, so I'd publish it as v1.
We could also add above as defaults, which resulted in ~10% faster test runs in my case.

cc: @Meligy

**Comment by Meligy** [comment]
As someone who got bitten by inclusion of RxJS, I'd really say please do not include it.

It should show an error, which tells people that they are missing something.

Since this project is meant for the Angular CLI, I'd suggest it should be as close as possible to what it puts in `src/test.ts` ([source](https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/blueprints/ng/files/__path__/test.ts)).

Only add stuff that is required to get jest running, and if possible, try to use the `polyfills.ts` that is already in the project as well. People can use this for common RxJS operators if they want.

**Comment by Meligy** [comment]
And, on another side, something that I have not mentioned but really should have: This project is SUPER AWESOME, and does make what seemed a very tough job become super nice. Thanks heaps.

**Comment by thymikee** [comment]
Yeah, so we can't really use `polfills.ts` because it includes browser version of Zone. However we can import frequent `rxjs` operators (like `map`) in the `setupJest.ts` file. I'll post a guide later today.
