### ISSUE TITLE
[Bug]: Cannot find module

### ISSUE THREAD

**Issue by DPShillcock** [thymikee/jest-preset-angular#1730]
### Version

8.31.1

### Steps to reproduce

Package versions

```
@angular-devkit/architect       0.1002.4
@angular-devkit/build-angular   14.1.3
@angular-devkit/core            14.1.3
@angular-devkit/schematics      12.2.0
@angular/cdk                    14.1.2
@angular/cli                    12.2.0
@angular/flex-layout            14.0.0-beta.40
@angular/material               14.1.2
@schematics/angular             12.2.0
rxjs                            6.6.7
typescript                      4.6.4`
```

angular.json test object

```
"test": {
          "builder": "@angular-builders/jest:run",
          "options": {
            "main": ["setupJest.ts"],
            "tsConfig": "src/tsconfig.spec.json",
            "no-cache": true
          }
        }

```

setupJest.ts

```
import { getTestBed } from '@angular/core/testing';
import {
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting,
} from '@angular/platform-browser-dynamic/testing';
import 'jest-preset-angular/setup-jest';
import 'zone.js';
import 'zone.js/testing';

getTestBed().initTestEnvironment(
  BrowserDynamicTestingModule,
  platformBrowserDynamicTesting(),
  {
    teardown: { destroyAfterEach: true },
  }
);

Object.defineProperty(window, 'CSS', { value: null });
Object.defineProperty(window, 'getComputedStyle', {
  value: () => {
    return {
      display: 'none',
      appearance: ['-webkit-appearance']
    };
  }
});
Object.defineProperty(document, 'doctype', {
  value: '<!DOCTYPE html>'
});
Object.defineProperty(document.body.style, 'transform', {
  value: () => {
    return {
      enumerable: true,
      configurable: true
    };
  }
});

```
`ng test` produces error on each test.

### Expected behavior

Run test suite when running `ng test`

### Actual behavior

Cannot find module '@angular/core/testing' from 'node_modules/jest-preset-angular/build/setup-jest.js'

### Environment

```shell
npm: 8.15.1
node: 16.13.2
```

**Comment by ahnpnl** [comment]
You are using `@angular-builders/jest` which is not maintained in this repo. Please provide your reproduce scenario using https://github.com/thymikee/jest-preset-angular/tree/main/examples

Besides, the error indicates that you don't have `@angular/core` package installed. Please ensure you have the package.

**Comment by NickGeek** [comment]
I'm getting the exact same error. `@angular/core` is installed.

**Comment by Schirbak** [comment]
Hey! Ran into the same issue. In my case, I use Nx, but I don't think it matters. After some digging, I figured out that the issue was with the jest package resolver. Native jest package resolver (see jest-resolver in your "node_modules" folder) cannot read Angular packages because it expects a slightly different file structure.

So the goal of this library among other things is to replace native resolver with a custom implementation. This goes implicitly and is described in [this line](https://github.com/thymikee/jest-preset-angular/blob/v11.1.1/presets/index.js#L10). Note that this is an outdated version (11.1.1), in the latest version (12.2.3) this line has disappeared. I think it's because jest's native resolver has learned to read Angular packages.

How to fix?
Make sure you set the `preset` as `'jest-preset-angular'` in your `jest.config.js` file.
