### ISSUE TITLE
Update to Angular 7 breaks angular.json-configuration

### ISSUE THREAD

**Issue by philly-vanilly** [thymikee/jest-preset-angular#205]
Hi. I updated my project from Angular 6.4 to Angular 7.1 and now running the script:

`ng test app-name --coverage
`
gives me the error:

```
● Unrecognized CLI Parameters:

  Following options were not recognized:
  ["main", "polyfills", "tsConfig"]

  CLI Options Documentation:
  https://jestjs.io/docs/en/cli.html
```
The configuration for the test command in angular.json looks like this:

```
"test": {
  "builder": "@angular-builders/jest:run",
  "options": {
    "main": "apps/app-name/src/test.ts",
    "polyfills": "apps/app-name/src/polyfills.ts",
    "tsConfig": "apps/app-name/tsconfig.spec.json",
    "configPath": "./jest.config.json",
    "styles": [
      "apps/app-name/src/styles.scss"
    ],
    "scripts": [],
    "assets": [
      "apps/app-name/src/favicon.ico",
      "apps/app-name/src/assets"
    ]
  }
},
```
Does the project support Angular 7 yet? If yes, how am I supposed to update the config to be compatible with Angular 7?

**Comment by ahnpnl** [comment]
hi @philly-vanilly, I tested this preset with a newly generated project by Angular CLI v7. Everything works normally for me. I see you are using `@angular-builders/jest` in your `angular.json`. I'd suggest you to contact the team of `@angular-builders/jest` regarding to your issue because they built the builder and the issue doesn't seem to be related to this preset.
