### ISSUE TITLE
[Bug]: `typescript` is listed as a peerDependency,despite being directly `require`'d

### ISSUE THREAD

**Issue by amakhrov** [thymikee/jest-preset-angular#2054]
### Version

12.2.3

### Steps to reproduce

I have a project with `@angular-builders/jest`. When running `yarn install` I'm getting the following message (I guess it's more of a warning rather than an error):
> ➤ YN0002: │ @angular-builders/jest@npm:15.0.0 [41d74] doesn't provide typescript (p59633), requested by jest-preset-angular

[Yarn documentation for this error message](https://yarnpkg.com/advanced/error-codes#yn0002---missing_peer_dependency)

I believe it's an issue with this library, not with the consuming @angular-builders/jest or our app.

[According to `peerDependencies` doc](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#peerdependencies), a dep should be listed in `peerDependencies` when it's not directly `require`d by the lib code. Otherwise, it should be a regular `dependency`. As far as I can see, `jest-preset-angular` uses `typescript` directly

### Expected behavior

No warnings from Yarn when installing dependencies

### Actual behavior

> ➤ YN0002: │ @angular-builders/jest@npm:15.0.0 [41d74] doesn't provide typescript (p59633), requested by jest-preset-angular

### Additional context

Related PR: https://github.com/thymikee/jest-preset-angular/pull/1442

### Environment

```shell
System:
    OS: macOS 13.2.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 3.2.3 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  npmPackages:
    jest: 28.1.1 => 28.1.1
```

**Comment by michaelfaith** [comment]
I'm not sure I agree with the assertion that libraries that directly require/import a library should declare it as a `dependency` rather than `peerDependency`.  In fact, the Angular team's own documentation around creating libraries encourages you to use peer dependencies for libraries that a consuming app/project might already be directly importing, so-as not to create conflicting resolution issues  (https://angular.io/guide/creating-libraries#peer-dependencies).  They're specifically talking about `@angular/` libraries there, but I think the same logic applies to `typescript`.  Any Angular project will almost certainly have a version of `typescript` already installed.  So, by declaring it as `peerDependency`, the library author is just declaring a compatibility range.

**Comment by michaelfaith** [comment]
I'm not sure that I agree with the assertion that all libraries that you require/import should be declared as `dependencies` instead of `peerDependencies`.  It's generally a good practice, but it's not a strict guideline. Even that npm documentation doesn't suggest that's how you should always do it.  In fact the Angular documentation on building Angular libraries encourages you to use peer dependencies for any `@angular/` libraries, because it's reasonable to assume that the consuming app/project will already be pulling those libraries in directly, and you wouldn't want to have two different versions of those packages being used.  I think the same logic could apply to `jest` and `typescript`.  It's reasonable to assume that any Angular project will already have `typescript` declared within their package.  The peer dependency declaration is meant to express compatability.

**Comment by ahnpnl** [comment]
I agree with @michaelfaith It's best practice to put `typescript` as `dependencies` in general. However, in this case we can relax that because Angular always goes together with `typescript`, which was also the original idea of this package to not include `typescript` directly.
