### ISSUE TITLE
upgrade peer dependency to jest 24

### ISSUE THREAD

**Issue by markgoho** [thymikee/jest-preset-angular#223]
Jest 24 was released yesterday, Jan 25. It looks like there are quite a few breaking changes. What needs to be done to help this library upgrade it's pear dependency to Jest 24?

**Comment by ahnpnl** [comment]
We are still discussing about whether we switch from `ts-jest` to use `@babel/preset-typescript` since jest 24 supports ts by default. That is the most concerned point at this moment. Besides, I saw there is a small change in jest config like deprecated `setupTestFrameworkScriptFile`. I don't know what else changes in config of jest. 

@thymikee would you please summarize anything else change in jest config beside  `setupTestFrameworkScriptFile` ?

**Comment by SimenB** [comment]
> We are still discussing about whether we switch from `ts-jest` to use `@babel/preset-typescript` since jest 24 supports ts by default.

FWIW, personally I'd like to see `ts-jest` still be a thing - there's probably quite a few people that would like to typecheck their tests (and have Jest respect `tsconfig` etc, which we'll never do out of the box).

**Comment by lup0r** [comment]
> Just checked locally and Jest 24 works without any changes from our side (if you don't mind deprecation warning)

That is, if you don't have other presets or config. Because you can't use both old and new form together, which gives you an error.

**Comment by slawiko** [comment]
👍 
When we can expect release with this fix? Thanks in advance :)

**Comment by thymikee** [comment]
@slawiko It's released in `next` tag as `7.0.0-alpha.5`
