### ISSUE TITLE
[Bug]: It is not work After config useESM: true

### ISSUE THREAD

**Issue by zhouyali** [thymikee/jest-preset-angular#2247]
### Version

12.2.3

### Steps to reproduce

`transform: {
		'^.+\\.(ts|js|mjs|html|svg)$': [
			'jest-preset-angular',
			{
				useESM: true,
			},
		],
	},

	transformIgnorePatterns: [
		'<rootDir>/node_modules/(?!(.*\\.mjs$|tslib|@elf|lit-elemen|lit-html|tr-grid-util|tr-grid-titlewrap|d3-color|uuid))',
	],`
	
	 another try
	 
`
	 jest.mock('./miscellaneous/uuid', () => {
    return {
      v4: jest.fn(() => 1)
    };
  });`
  
![1](https://github.com/thymikee/jest-preset-angular/assets/19162568/7bf37a5e-10fd-4b26-ae39-508c6576efe4)
![2](https://github.com/thymikee/jest-preset-angular/assets/19162568/0325dc48-5d24-4e98-a733-e890a8001210)
![3](https://github.com/thymikee/jest-preset-angular/assets/19162568/8b144197-783c-4b87-8285-437b645fe8b1)
![4](https://github.com/thymikee/jest-preset-angular/assets/19162568/87ae8a66-7402-4281-bc33-be7602bb6f84)

### Expected behavior

I expect the uuid on transformIgnorePatterns will be compile successfully 

### Actual behavior

Test suite failed to run

RangeError: Maximum call stack size exceeded.

### Additional context

it is a internal project, so it's not allowed to post repo here, the  transform and  transformIgnorePatterns config work for other es module package, but not work for all esm.

### Environment

```shell
System :
Windows64
Env:
"jest-preset-angular": "^12.2.3", 
"jest": "^28.1.3",
"@angular/core": "^14.2.12"
```

**Comment by ahnpnl** [comment]
You can try to use https://github.com/thymikee/jest-preset-angular/tree/main/examples to create a small reproduce case, that would help a lot

**Comment by Delagen** [comment]
try moduleMapper
` '^uuid$': require.resolve('uuid'),`
instead of adding to transformignore

**Comment by ahnpnl** [comment]
thanks @Delagen , @zhouyali besides, you can also put the configuration like this in your Jest config
```
{
   //....
   moduleNameMapper: {
       uuid: '<rootDir>/node_modules/uuid/dist/index.js',
   }
}
```

The error you got which was caused by default Jest module resolution which looks for the `default` field inside `exports` of `package.json`
<img width="498" alt="image" src="https://github.com/thymikee/jest-preset-angular/assets/27772165/96bd3374-2074-4e51-9a1b-10a45d23c24a">

However, because Jest runs with JSDOM, which is entirely in NodeJs environment therefore the file under `esm-browser` can't be used. We need to tell Jest to load the file from `node` export instead.
