### ISSUE TITLE
[Bug]: Import in component is undefined under test

### ISSUE THREAD

**Issue by lukasmatta** [thymikee/jest-preset-angular#2339]
### Version

14.0.3

### Steps to reproduce

1. Clone https://github.com/lukasmatta/JestImportError
2. `npm install`
3. Run app - `ng serve` - everything works
4. Run tests `npx jest` - fails because Quill import is undefined

### Expected behavior

I expect the quill import to behave the same in the app build and test.

### Actual behavior

When `esModuleInterop` is not set to true, `import Quill from "quill"` results in the `Quill` being `undefined` when inside the test. On the other side, import works fine when running the app using the `ng serve`. What's causing this difference?

### Additional context

When using Karma&Jasmine to run the test, import behavior is consistent comparing app serve and the test.

Note, that I'm aware that the error can be solved simply by setting `esModuleInterop` to `true`, but I'd like to find out the underlying reason, why is it behaving differently when inside the test and when served.

### Environment

```shell
System:
    OS: macOS 14.3.1
    CPU: (12) arm64 Apple M2 Pro
  Binaries:
    Node: 20.11.0 - ~/.nvm/versions/node/v20.11.0/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.0/bin/npm
  npmPackages:
    jest: ^29.7.0 => 29.7.0
```

**Comment by ahnpnl** [comment]
This usually happens because Jest has a different way to resolve files from `node_modules` comparing to Angular CLI.

Normally, the solution is trying to know which file Angular CLI tried to load. In this case, since Angular app is served on browser mainly, Angular CLI will try to load ESM version of Quill.

I think you can look into `quill` folder in `node_modules` to see which file is ESM, or try using Jest in ESM mode, which is documented in our documentation website

**Comment by ahnpnl** [comment]
If you wish to have the closest behavior to Karma/Jasmine, you should use Jest in ESM mode. By default, Jest runs with CommonJS. In the example app, there is the command to run ESM mode. 

In ESM mode, you can freely turn off `esModuleInterop` and `quill` will still work.

For CommonJS, it is required to turn it on.
