### ISSUE TITLE
Example doesn't work

### ISSUE THREAD

**Issue by NagRock** [thymikee/jest-preset-angular#256]
Hi, I've cloned repository. Installed dependencies in `example` folder. And when running `yarn test` I get:
```
Validation Error:

Module jest-preset-angular should have "jest-preset.js" or "jest-preset.json" file at the root.
```

I see that this file is in root. I've also copied it to example folder and example/src but same error appears.

**Comment by thymikee** [comment]
have you run `yarn` in both root and `example/` directories?

**Comment by webdevelopland** [comment]
Is there alternative with `npm`? Angular developers don't use yarn.

**Comment by ahnpnl** [comment]
Npm or yarn is the same :)

**Comment by webdevelopland** [comment]
1. `yarn add -D jest jest-preset-angular` fixes the issue
2. You don't need to run it in root. Running it in `example` directory is enough to run the example
3. npm and yarn are not the same. After running `npm install` the issue still comes.

So, maybe there is a way to run some `npm` command, instead of `yarn add -D jest jest-preset-angular` ?

**Comment by ahnpnl** [comment]
"the same" means they work similar. The way to install dependencies between these 2 are similar. Npm install --dev = yarn add -D or similar. If yarn works, npm should work too.

**Comment by webdevelopland** [comment]
@ahnpnl Thanks!

For everyone you faced same issue:
`package.json` contain string: `"jest-preset-angular": "file:../"`
You need to replace it to: `"jest-preset-angular": "^7.0.1"`
Then run
```
npm i
```

**Comment by ahnpnl** [comment]
Actually we put it like that because when we want to develop a new feature/fix a bug before a release, the example app needs to test with the changes. So we need to link the example app to the source codes. I remember there were some issues when using this way but they were fixed already I think.

**Comment by wtho** [comment]
* **Works with yarn**
  ```
  yarn install
  cd example
  yarn install
  yarn test
  ```
* **Does not work with npm by default**
  ```
  npm install
  cd example
  npm install
  npm test
  ```
  Something like this will come up:
  ```
    ● Test suite failed to run
    Cannot find module 'core-js/es6/reflect' from 'setupJest.js'
  ```

The reason is the symlink strategy by npm. In the example folder itself peerDependencies like `@angular/...` or `core-js` are installed, but not in the root folder of the library. We do not need them there to publish and test the library.

When resolving dependencies, npm will only go UP and look for `node_modules` folders.

As the symlink created by `npm` links upwards to `../`, and as `core-js` is referenced in the preset in the parent folder, it will start to look for this dependency in the root folder `<repo>/node_modules` and upwards, but not in `<repo>/example/node_modules`. But it is not installed there.

`yarn` handles the sitation different. It actually copies the whole parent folder into `<repo>/example/node_modules/jest-preset-angular` and therefore `require('core-js')` in the preset can find the dependency in `<repo>/example/node_modules/core-js.

There are four solutions if you want to try out the example app:
* use `yarn` (install it using `npm i -g yarn`)
* install a `jest-preset-angular` version from npm, as @webdevelopland suggested using `npm i -D jest-preset-angular@latest`
* copy the root folder manually into `example/node_modules` using from inside `example`:
  ```
  rm node_modules/jest-preset-angular
  mkdir node_modules/jest-preset-angular
  cp -r ../AngularSnapshotSerializer.js ../HTMLCommentSerializer.js ../index.js ../InlineHtmlStripStylesTransformer.js ../jest-preset.js ../package.json ../setupJest.js ../zone-patch  node_modules/jest-preset-angular
  ```
