### ISSUE TITLE
Full 'Jasmine' error does not show in the test output

### ISSUE THREAD

**Issue by jusefb** [thymikee/jest-preset-angular#30]
First of all thanks for a great tool, I am finally seeing the possibility of doing productive TDD with Angular + Webpack projects. Here is an issue I have found though. When testing Angular 4 components it is not possible to diagnose injection errors in the console output. It looks like the Jasmine error that is thrown in the beforeEach block of the test is not being captured properly. Not sure if this is a jest issue or if something can be added to the jest-preset-angular to get this to work. See screenshot below for the error difference between Jasmine Reporter output and Jest.

![image](https://cloud.githubusercontent.com/assets/3741868/25565425/309cbfbc-2dbe-11e7-8320-bf27609ea3fb.png)

**Comment by thymikee** [comment]
I've bumped into this issue too, it sucks 🙁. 
Seems like Zone is messing with some of the (not all) error messages, and doesn't put `message` field into `stack` of the `Error`, which is a common practice I'll try to work on this, but it either needs to be fixed in Zone or Jest (hopefully we can do something here).

**Comment by jusefb** [comment]
Great thanks

**Comment by thymikee** [comment]
Fingers crossed: https://github.com/facebook/jest/pull/3513

**Comment by thymikee** [comment]
Good news! This will be fixed in next patch release.

**Comment by SergeyKuryatnick** [comment]
@thymikee 
Great thanks for advice about `zone.js`
