### ISSUE TITLE
snapshot test passes when text changes made since last snapshot

### ISSUE THREAD

**Issue by tony1377** [thymikee/jest-preset-angular#32]
Hi, first off good job on getting this working, it's great to have jest on ng2!

I was testing out the snapshot feature by taking a snapshot of the a fresh new ng cli app using this
 example here

 https://github.com/thymikee/jest-preset-angular/blob/master/example/src/app/app.component.spec.ts#L25

 then I changed app.component.html from

 ```
<h1>
  {{title}}
</h1>

 ```

 to

 ```

 <h1>
   {{title}} - some random text here
 </h1>

 ```

Then I ran the tests again and the snapshot test passed. It does fail if I remove the `{{title}}`.
   
Is this a bug or am I misunderstanding the scope of the snapshot testing?

**Comment by thymikee** [comment]
Adding random "some random text here" pass, because it's (wrongly) not stored in snapshot. This is a limitation we have to deal with until Jest 20 is released (there's a bug in current version, already fixed on master). So it's pretty ok you got confused.

By removing `{{title}}` from your template, you change the output of the component and therefore the new snapshot is different that original (stored on your hard drive). That's why it fails – now you must decide if:
* this is intended change and run `jest -u` (or press `u` in watch mode) or 
* this is a bug and you need to fix it.

**Comment by tony1377** [comment]
Ah I see, this limitation, does it only ignore text which is also inside a node with a variable or are there other 
scenarios that it effects as well?
 
Also, any idea roughly when jest 20 will be out?

**Comment by thymikee** [comment]
It's for Text nodes, so `<el>{{text}}</el>`, `<el>some text</el>` will work, but ```<el>{{text}}
 not showing</el>` will not, because it creates 2 text nodes. We're working pretty hard on releasing v20 this week.

**Comment by tony1377** [comment]
that's great news, looking forward to it :)
