### ISSUE TITLE
Syntax Error when using Jest in VMWare Clarity

### ISSUE THREAD

**Issue by whizkidwwe1217** [thymikee/jest-preset-angular#341]
# Syntax Error when using Jest in VMWare Clarity

fter the @clr/core dependency of @clr/angular was introduced in 3.0, Jest is now throwing a syntax error coming from the new package.
Original issue filed at: https://github.com/vmware/clarity/issues/4196

```
node_modules\@clr\core\fesm2015\clr-core.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { __decorate, __metadata, __awaiter } from 'tslib';
                                                                                                    ^

    SyntaxError: Unexpected token {

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)    
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)
      at node_modules/@clr/angular/bundles/clr-angular.umd.js:2:156
      at Object.<anonymous> (node_modules/@clr/angular/bundles/clr-angular.umd.js:5:2)

Test Suites: 2 failed, 4 passed, 6 total
Tests:       16 passed, 16 total
```

Reproduction:

1. Clone this repo: https://github.com/whizkidwwe1217/jest-test
2. Run `npm install`, then `npm test`.

**Comment by whizkidwwe1217** [comment]
Another error is thrown when I add a
```
transform: {
    "^.+\\.ts?$": "ts-jest"
  },
```
![image](https://user-images.githubusercontent.com/1977391/72326391-1b826900-36ea-11ea-92bf-9dc757f7e3f1.png)

**Comment by ahnpnl** [comment]
Hi,

The error you had is caused by incorrect tsconfig.spec.json. What you should do:
- Add module: commonjs and target es5 to your tsconfig.spec.json.
- Clear jest cache.
- Run tests again

Besides you don’t need to add transform because jest-preset-angular already set that for you.

**Comment by wtho** [comment]
Please have a look at the [Readme#Custom-TSConfig](https://github.com/thymikee/jest-preset-angular#custom-tsconfig).

If this solved your problem, please close this issue.
Cheers!

**Comment by whizkidwwe1217** [comment]
@ahnpnl @wtho I did your suggestions but it didn't work. Is there anything I'm missing? I never had a problem with this using Karma but I want to use Jest because it's faster.

![image](https://user-images.githubusercontent.com/1977391/72732989-ef775400-3bd1-11ea-929b-429ff56ca3ec.png)

I need to be able to compile the dependency to ES6 as per comment from the author: https://github.com/vmware/clarity/issues/4196#issuecomment-573950091

**Comment by wtho** [comment]
Ok, so first, as your configuration of `globals.ts-jest` looks exactly as the one in our preset, you can omit it in your `jest.config.js`. There is no need to override it.

Second, this is an issue with `moduleNameMapper`, as the error message suggests. This means, Compilation of Angular components using `ts-jest` generally works (and so the functionality this package supplies)!

It seems like some package in `node_module` does serve `ts` or `es6` sources, so you have to tell ts-jest to compile these to es5, so jsdom (and jest) can use it. I would recommend to add `allowJs: true` to `tsconfig.spec.json`, otherwise it will ignore all `.js` files and leave them as-is.

Otherwise I think you should head over to the `ts-jest` repository to solve this. Search in their issues, there should be some (closed ones) that had the same problem.

Cheers!

**Comment by ahnpnl** [comment]
@whizkidwwe1217 FYI https://github.com/nrwl/nx/issues/812#issuecomment-429440745

**Comment by whizkidwwe1217** [comment]
My problems solved via https://github.com/thymikee/jest-preset-angular/issues/301

> Please have a look at the [Readme#Custom-TSConfig](https://github.com/thymikee/jest-preset-angular#custom-tsconfig).
> 
> If this solved your problem, please close this issue.
> Cheers!

I missed to read this comment.
@ahnpnl @wtho  Thank you so much!
