### ISSUE TITLE
Ionic with jest -- Coverage not 100%

### ISSUE THREAD

**Issue by gabrielseco** [thymikee/jest-preset-angular#40]
I am trying to use ionic with jest and jest-preset-angular.

When I do a simple test for a reducer with the library ngrx I can't get the 100% of the coverage.

If you could give me some feedback, it would be appreciated.

You can reproduce it in the next repo

https://github.com/gabrielseco/jest-ionic-example

You can do a npm i and start the project with npm start or jump to the tests with npm run test:watch 
I am attaching a pic of the coverage
<img width="1260" alt="captura de pantalla 2017-05-28 a las 11 22 27" src="https://cloud.githubusercontent.com/assets/7215480/26527642/030ce6cc-4398-11e7-831d-d5e9beae86f2.png">

**Comment by thymikee** [comment]
Unfortunately there's nothing this preset can do to fix it. It seems like coverage is being wrongly generated for TypeScript here. I encourage you to create a minimal repro (just a reducer with action test) and file an issue in IstanbulJS – it's the tool that generates the coverage: https://github.com/istanbuljs/istanbuljs.
Or you can check out `ts-jest`: https://github.com/kulshekhar/ts-jest

Btw, the coverage goes to 100% if you use `Object.assign` instead of object spread and `ADD_ITEM` instead of `todo.ADD_ITEM`.
