### ISSUE TITLE
ts-jest is not installed properly

### ISSUE THREAD

**Issue by Tallyb** [thymikee/jest-preset-angular#59]
The `package.json` configuration 
`"bundleDependencies": false,`
is incorrect (array expected), and cause ts-jest to be incorrectly installed under inner `node_modules`, which in some cases may cause jest not to find it. Should be installed on top level `node_modules`

**Comment by thymikee** [comment]
Can you elaborate on this? I'm not sure what's this about

**Comment by Tallyb** [comment]
`bundleDependencies` structure has changed to contain an array. The value `false` is not valid. 
I use npm 5.0.3 and the ts-jest was installed under `jest-preset-angular/node_modules` and not directly under `node_modules`. 
I now see that this property is generated in my installed package.json, and does not exist on the original one, so it may be some local configuration that is misbehaving.  
I am closing this issue.

**Comment by dominique-mueller** [comment]
Well, I'm having the same issue here. `ts-jest` is expected under `node_modules/ts-jest` -- but actually lives under `node_modules/jest-preset-angular/node_modules/ts-jest`. I'm assuming it has either something to do with npm v5, or some other updated dependency.

I got it working by:
- moving the `jest.config.json` Jest configuration file to the project root folder (before it was in a `config` subfolder)
- installing `ts-jest` into the root `node_modules` folder by adding it as a devDependency to my project

Still, this seems like an actual issue - but I'm not sure where the issue comes from (this preset, ts-jest, jest) ...

**Comment by thymikee** [comment]
Does it happen with npm v3/4 or Yarn?

**Comment by Tallyb** [comment]
I am not using yarn, and it happened to me also with npm 3. 
@dominique-mueller - do you use it in a lerna project?

**Comment by Tallyb** [comment]
@thymikee  maybe upgrading the tyoescript dev dependency will do the trick?

**Comment by thymikee** [comment]
@dominique-mueller you need to specify `rootDir` if your config is not in the root of your project (from where you run Jest). It's a bug in Jest 20, still unresolved

**Comment by thymikee** [comment]
@Tallyb my dev dependencies are not affecting your deps

**Comment by dominique-mueller** [comment]
@thymikee I'll try that one out, thanks!

**Comment by dominique-mueller** [comment]
@thymikee Awesome, defining the `rootDir` fixed it! Thanks so much!
