### ISSUE TITLE
Component Templates not correctly compiled

### ISSUE THREAD

**Issue by jensweigele** [thymikee/jest-preset-angular#842]
## 🐛 Bug Report

Using an undefined expression in a component template does not throw an error.

## To Reproduce

- setup an angular project with jest (e.g. via nx)
- take a spec file and make use of an undefined identifier (e.g. add '[ngClass]="someThingABC"' to a div)
- run the tests

## Expected behavior

I would expect that the test should fail, since "someThingABC" is not defined. That's at least the behavior of Karma+Jasmine and also the Angular Compiler is throwing this error when building the project.

If I write "someThingABC()" the test fails, since a call of undefined is executed.
If I do something like "doLog(someThingABC)" and print out the arguments of "doLog", I get "undefined".
So it looks like that unknown variables/expressions are just resolved to "undefined" instead of throwing an compile time error.

## Link to repo (highly encouraged)

https://github.com/jensweigele/jest-angular-issue
Clone
run yarn install
run yarn nx test

## envinfo

```
System:
    OS: MacOS BigSur

Npm packages:
    jest: 26.2.2 (but also tried with 27.0.0-next.3)
    jest-preset-angular: 8.3.2 (but also tried with 9.0.0-next.8)
    typescript: 4.0.3 (but also tried with 4.1.5)
```

**Comment by wtho** [comment]
As at runtime, any undeclared variable is valid to be referenced in JavaScript, this is actually a valid case.

In `jest-preset-angular` v8 and below we only use TypeScript, but no Angular Type Checking. This preset basically does just achieve to gap the small bridge between running an Angular App in JSDOM instead of the browser, leveraging `ts-jest`'s compilation checks.

As the TypeScript compiler itself does not know of Angular Templates and jest-preset-angular just passes the templates as-is to the Angular JIT-Compiler, there is no component which would do this extra-effort to check it.

-----

But - there is hope! @ahnpnl is currently working on a Jest Transformer which will take full advantage of the Angular Compiler and support testing with ivy, and it should be able to detect these issues. Feel free to try it out using `jest-preset-angular@next`.
Maybe you can do so and give some feedback, if this worked for you.

Cheers and happy coding!

**Comment by jensweigele** [comment]
Thanks for the brief explanation.

I think I tested this with the beta versions of js-test, js-preset-angular and jest - but got the same results.

I'm going to upgrade the demo project to those versions and give it another try!

**Comment by jensweigele** [comment]
I've updated the packages  to:
```
    "jest": "27.0.0-next.3",
    "jest-preset-angular": "9.0.0-next.8",
    "ts-jest": "27.0.0-next.7",

```

But unfortunately I'm still seeing the same result. I've updated the sample-repo if you want to have a look!

**Comment by ahnpnl** [comment]
I tested with Karma + Jasmine by adding something like
```
<h3>{{ foo }} </h3>
```

and I see test still passes
![image](https://user-images.githubusercontent.com/27772165/109228836-bc36c980-77c2-11eb-9e02-15a15d82ca4e.png)

Note that tests run in JIT mode, full template type check is only possible with AOT

**Comment by jensweigele** [comment]
Shame on me - I'm sorry.
I could have sworn that such errors are thrown by Karma+Jasmine.

Is there any chance to enable AOT for testing with jest?

**Comment by ahnpnl** [comment]
Currently AOT test is not yet possible, even with Karma + Jasmine, see WIP https://github.com/angular/angular-cli/pull/16369

we are doing exactly like angular-cli so AOT test we have to wait :)

**Comment by kddsultan** [comment]
> WIP [angular/angular-cli#16369](https://github.com/angular/angular-cli/pull/16369)

@ahnpnl, thanks for the clarification first of all. Do you know what the result was for the WIP PR? Since it is now closed one cannot even ask that in that discussion.

**Comment by ahnpnl** [comment]
I didn’t follow the result of WIP, seem like it didn’t go anywhere or something else happened.
